[build]
  command = "npm run build:optimized"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9.6.7"
  NPM_FLAGS = "--no-fund --no-audit --silent"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_OPTIONS = "--max-old-space-size=2048"
  NEXT_TELEMETRY_DISABLED = "1"
  GENERATE_SOURCEMAP = "false"
  # Skip ESLint during builds to prevent failures
  SKIP_ESLINT = "true"
  # Disable TypeScript checking during builds
  SKIP_TYPE_CHECK = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000

[functions]
  node_bundler = "esbuild"

# Headers for enhanced security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff" 
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.googleapis.com https://*.firebase.com https://*.firebaseapp.com wss://*.firebase.com;"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]  
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200